//Anomalous crystal effects
#define ANOM_CRYSTAL_FIRE 1
#define ANOM_CRYSTAL_EMP 2
#define ANOM_CRYSTAL_GRAVITATIONAL 3
#define ANOM_CRYSTAL_EXPLOSIVE 4
#define ANOM_CRYSTAL_RESIN_FOAM 5
#define ANOM_CRYSTAL_NITROUS_OXIDE 6
#define ANOM_CRYSTAL_RADIATION 7
#define ANOM_CRYSTAL_MEDICAL_FOAM 8
#define ANOM_CRYSTAL_TOXIN_FOAM 9
#define ANOM_CRYSTAL_ELECTRIC 10
#define ANOM_CRYSTAL_FROST_VAPOUR 11
//MAKE SURE TO UPDATE THIS!!
#define ANOM_CRYSTAL_EFFECTS_IN_TOTAL 11
